init commit for dev-3.0

diff --git a/ezctl b/ezctl
--- a/ezctl
+++ b/ezctl
@@ -1,36 +1,52 @@
 #!/bin/bash
-# 
-# This script aims to manage k8s clusters created by 'kubeasz'. (developing)
+#  Create & manage k8s clusters by 'kubeasz'
 
 set -o nounset
 set -o errexit
 #set -o xtrace
 
 function usage() {
+    echo -e "\033[33mUsage:\033[0m ezctl COMMAND [args]"
     cat <<EOF
-Usage: easzctl COMMAND [args]
+-------------------------------------------------------------------------------------
+Cluster setups:
+    list		             to list all of the managed clusters
+    new         <cluster>            to start a new k8s deploy with name 'cluster'
+    setup       <cluster>  [step]    to setup a cluster, also supporting a step-by-step way
+    start-aio		             to quickly setup an all-in-one cluster with 'default' settings
 
-Cluster-wide operation:
-    checkout		To switch to context <clustername>, or create it if not existed
-    destroy		To destroy the current cluster, '--purge' to also delete the context
-    list		To list all of clusters managed
-    setup		To setup a cluster using the current context
-    start-aio		To quickly setup an all-in-one cluster for testing (like minikube)
+Cluster ops:
+    add-etcd    <cluster>  <args>    to add a etcd-node to the etcd cluster
+    add-master  <cluster>  <args>    to add a master node to the k8s cluster
+    add-node    <cluster>  <args>    to add a work node to the k8s cluster
+    del-etcd    <cluster>  <ip>      to delete a etcd-node from the etcd cluster
+    del-master  <cluster>  <ip>      to delete a master node from the k8s cluster
+    del-node    <cluster>  <ip>      to delete a work node from the k8s cluster
+    upgrade     <cluster>            to upgrade the k8s cluster
+    destroy     <cluster>            to destroy the current cluster, '--purge' to also delete the context
 
-In-cluster operation:
-    add-etcd		To add a etcd-node to the etcd cluster
-    add-master		To add a kube-master(master node) to the k8s cluster
-    add-node		To add a kube-node(work node) to the k8s cluster
-    del-etcd		To delete a etcd-node from the etcd cluster
-    del-master		To delete a kube-master from the k8s cluster
-    del-node		To delete a kube-node from the k8s cluster
-    upgrade		To upgrade the k8s cluster
-
-Extra operation:
-    basic-auth   	To enable/disable basic-auth for apiserver
-
-Use "easzctl help <command>" for more information about a given command.
+Use "ezctl help <command>" for more information about a given command.
 EOF
+}
+
+function logger() {
+  TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')
+  case "$1" in
+    debug)
+      echo -e "$TIMESTAMP \033[36mDEBUG\033[0m $2"
+      ;;
+    info)
+      echo -e "$TIMESTAMP \033[32mINFO\033[0m $2"
+      ;;
+    warn)
+      echo -e "$TIMESTAMP \033[33mWARN\033[0m $2"
+      ;;
+    error)
+      echo -e "$TIMESTAMP \033[31mERROR\033[0m $2"
+      ;;
+    *)
+      ;;
+  esac
 }
 
 function help-info() {
@@ -53,9 +69,6 @@ function help-info() {
         (del-node)
             echo -e "Usage: easzctl del-node <node_ip>\n\nread 'https://github.com/easzlab/kubeasz/blob/master/docs/op/op-node.md'"
             ;;
-        (basic-auth)
-            echo -e "Usage: easzctl basic-auth <options>\nOption:\t -s enable basic-auth\n\t -S disable basic-auth\n\t -u <user> set username\n\t -p <pass> set password"
-            ;;
         (*)
             usage
             return 0
@@ -63,11 +76,58 @@ function help-info() {
     esac
 }
 
-function process_cmd() {
-    echo -e "[INFO] \033[33m$ACTION\033[0m : $CMD"
-    $CMD || { echo -e "[ERROR] \033[31mAction failed\033[0m : $CMD"; return 1; }
-    echo -e "[INFO] \033[32mAction successed\033[0m : $CMD"
+### Cluster setups functions ##############################
+
+function new() {
+    # check if already existed
+    [[ -d "clusters/$1" ]] && { logger error "cluster: $1 already existed"; exit 1; }
+    [[ "$1" == default ]] && { logger error "name 'default' is reserved for `ezctl start-aio`"; exit 1; }
+
+    logger debug "generate custom cluster files in clusters/$1"
+    mkdir -p "clusters/$1"
+    cp example/hosts.multi-node "clusters/$1/hosts"
+    sed -i "s/_cluster_name_/$1/g" "clusters/$1/hosts"
+    cp example/config.yml "clusters/$1/config.yml"
+
+    logger debug "cluster $1: files successfully created."
+    logger info "next steps 1: to config 'clusters/$1/hosts'"
+    logger info "next steps 2: to config 'clusters/$1/config.yml'"
 }
+
+function setup() {
+    [[ -d "clusters/$1" ]] || { logger error "invalid config, run 'ezctl new $1' first"; return 1; }
+    [[ -f "bin/kube-apiserver" ]] || { logger error "no binaries founded, run 'ezdown -D' fist"; return 1; }
+
+    logger info "\n cluster:$1 setup begins in 5s, press any key to abort\n:"
+    ! (read -t5 -n1 ANS) || { logger warn "setup aborted"; return 1; }
+
+    ansible-playbook -i "clusters/$1/hosts" -e "@clusters/$1/config.yml" playbooks/90.setup.yml || return 1
+}
+
+function list() {
+    [ -f "$BASEPATH/.cluster/current_cluster" ] || { echo "[ERROR] invalid context, run 'easzctl checkout <cluster_name>' first"; return 1; }
+    CLUSTER=$(cat $BASEPATH/.cluster/current_cluster)
+    echo -e "\nlist of managed contexts (current: \033[33m$CLUSTER\033[0m)"
+    i=1; for c in $(ls $BASEPATH/.cluster/ |grep -Ev "backup|ssl|current_cluster|kubeconfig");
+    do
+        echo -e "==> context $i:\t$c"
+        let "i++"
+    done
+    echo -e "\nlist of installed clusters (current: \033[33m$CLUSTER\033[0m)"
+    i=1; for c in $(ls $BASEPATH/.cluster/ |grep -Ev "backup|ssl|current_cluster|kubeconfig");
+    do
+        KUBECONF=$BASEPATH/.cluster/$c/config
+        if [ -f "$KUBECONF" ]; then
+            echo -e "==> cluster $i:\t$c"
+            $BASEPATH/bin/kubectl --kubeconfig=$KUBECONF get node
+        fi
+        let "i++"
+    done
+}
+
+
+
+
 
 ### in-cluster operation functions ##############################
 
@@ -256,34 +316,6 @@ function install_context() {
     fi
 }
 
-function checkout() {
-    # check directory '.cluster', initialize it if not existed
-    if [ ! -f "$BASEPATH/.cluster/current_cluster" ]; then
-        echo "[INFO] initialize directory $BASEPATH/.cluster"
-        mkdir -p $BASEPATH/.cluster/default
-        echo default > $BASEPATH/.cluster/current_cluster
-    fi
-
-    # check if $1 is already the current context
-    CLUSTER=$(cat $BASEPATH/.cluster/current_cluster)
-    [ "$1" != "$CLUSTER" ] || { echo "[WARN] $1 is already the current context"; return 0; }
-
-    echo "[INFO] save current context: $CLUSTER"
-    save_context
-    echo "[INFO] clean context: $CLUSTER"
-    rm -rf $BASEPATH/hosts /root/.kube/* $BASEPATH/.cluster/ssl $BASEPATH/.cluster/kube-proxy.kubeconfig
-
-    # check context $1, install it if existed, otherwise initialize it using default context
-    if [ ! -d "$BASEPATH/.cluster/$1" ];then
-        echo "[INFO] context $1 not existed, initialize it using default context"
-        cp -rp $BASEPATH/.cluster/default $BASEPATH/.cluster/$1
-        rm -f $BASEPATH/.cluster/$1/hosts $BASEPATH/.cluster/$1/config
-    fi
-    echo "[INFO] change current context to $1"
-    echo $1 > $BASEPATH/.cluster/current_cluster
-    install_context;
-}
-
 function setup() {
     [ -f "$BASEPATH/.cluster/current_cluster" ] || { echo "[ERROR] invalid context, run 'easzctl checkout <cluster_name>' first"; return 1; }
     [ -f "$BASEPATH/bin/kube-apiserver" ] || { echo "[ERROR] no binaries found, download then fist"; return 1; }
@@ -405,7 +437,7 @@ function basic-auth(){
 
 ### Main Lines ##################################################
 
-BASEPATH=/etc/ansible
+BASEPATH=/etc/kubeasz
 
 [ "$#" -gt 0 ] || { usage >&2; exit 2; }
 
diff --git a/ezdown b/ezdown
--- a/ezdown
+++ b/ezdown
@@ -2,9 +2,9 @@
 #--------------------------------------------------
 # This script is for: 
 # 1. to download the scripts/binaries/images needed for installing a k8s cluster with kubeasz
-# 2. to run kubeasz in a container (optional, not recommend)
+# 2. to run kubeasz in a container (optional)
 # @author:   gjmzj
-# @usage:    ./easzup
+# @usage:    ./ezdown
 # @repo:     https://github.com/easzlab/kubeasz
 # @ref:      https://github.com/kubeasz/dockerfiles
 #--------------------------------------------------
@@ -12,7 +12,7 @@ set -o nounset
 set -o errexit
 #set -o xtrace
 
-# default version, can be overridden by cmd line options, see ./easzup
+# default version, can be overridden by cmd line options, see usage
 DOCKER_VER=19.03.14
 KUBEASZ_VER=2.2.3
 K8S_BIN_VER=v1.20.1
@@ -28,38 +28,75 @@ flannelVer=v0.13.0-amd64
 metricsVer=v0.3.6
 pauseVer=3.2
 
+function usage() {
+  echo -e "\033[33mUsage:\033[0m ezdown [options] [args]"
+  cat <<EOF
+  option: -{DdekSz}
+    -C         stop&clean all local containers
+    -D         download all into "$BASE"
+    -P         download system packages for offline installing
+    -S         start kubeasz in a container
+    -d <ver>   set docker-ce version, default "$DOCKER_VER"
+    -e <ver>   set kubeasz-ext-bin version, default "$EXT_BIN_VER"
+    -k <ver>   set kubeasz-k8s-bin version, default "$K8S_BIN_VER"
+    -m <str>   set docker registry mirrors, default "CN"(used in Mainland,China)
+    -p <ver>   set kubeasz-sys-pkg version, default "$SYS_PKG_VER"
+    -z <ver>   set kubeasz version, default "$KUBEASZ_VER"
+
+see more at https://github.com/kubeasz/dockerfiles
+EOF
+}
+
+function logger() {
+  TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')
+  case "$1" in
+    debug)
+      echo -e "$TIMESTAMP \033[36mDEBUG\033[0m $2"
+      ;;
+    info)
+      echo -e "$TIMESTAMP \033[32mINFO\033[0m $2"
+      ;;
+    warn)
+      echo -e "$TIMESTAMP \033[33mWARN\033[0m $2"
+      ;;
+    error)
+      echo -e "$TIMESTAMP \033[31mERROR\033[0m $2"
+      ;;
+    *)
+      ;;
+  esac
+}
+
 function download_docker() {
-  echo -e "[INFO] \033[33mdownloading docker binaries\033[0m $DOCKER_VER"
   if [[ "$REGISTRY_MIRROR" == CN ]];then
     DOCKER_URL="https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/static/stable/x86_64/docker-${DOCKER_VER}.tgz"
   else
     DOCKER_URL="https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VER}.tgz"
   fi
 
-  mkdir -p /opt/kube/bin /etc/ansible/down /etc/ansible/bin
-  if [[ -f "/etc/ansible/down/docker-${DOCKER_VER}.tgz" ]];then
-    echo "[INFO] docker binaries already existed"
+  if [[ -f "$BASE/down/docker-${DOCKER_VER}.tgz" ]];then
+    logger warn "docker binaries already existed"
   else
-    echo -e "[INFO] \033[33mdownloading docker binaries\033[0m $DOCKER_VER"
+    logger info "downloading docker binaries, version $DOCKER_VER"
     if [[ -e /usr/bin/curl ]];then
-      curl -C- -O --retry 3 "$DOCKER_URL" || { echo "[ERROR] downloading docker failed"; exit 1; }
+      curl -C- -O --retry 3 "$DOCKER_URL" || { logger error "downloading docker failed"; exit 1; }
     else
-      wget -c "$DOCKER_URL" || { echo "[ERROR] downloading docker failed"; exit 1; }
+      wget -c "$DOCKER_URL" || { logger error "downloading docker failed"; exit 1; }
     fi
-    /bin/mv -f ./docker-${DOCKER_VER}.tgz /etc/ansible/down
+    /bin/mv -f ./docker-${DOCKER_VER}.tgz $BASE/down
   fi
 
-  tar zxf /etc/ansible/down/docker-${DOCKER_VER}.tgz -C /etc/ansible/down && \
-  /bin/cp -f /etc/ansible/down/docker/* /etc/ansible/bin && \
-  /bin/mv -f /etc/ansible/down/docker/* /opt/kube/bin && \
+  tar zxf $BASE/down/docker-${DOCKER_VER}.tgz -C $BASE/down && \
+  /bin/cp -f $BASE/down/docker/* $BASE/bin && \
+  /bin/mv -f $BASE/down/docker/* /opt/kube/bin && \
   ln -sf /opt/kube/bin/docker /bin/docker 
 }
 
 function install_docker() {
   # check if a container runtime is already installed
-  systemctl status docker|grep Active|grep -q running && { echo "[WARN] docker is already running."; return 0; }
+  systemctl status docker|grep Active|grep -q running && { logger warn "docker is already running."; return 0; }
  
-  echo "[INFO] generate docker service file"
+  logger debug "generate docker service file"
   cat > /etc/systemd/system/docker.service << EOF
 [Unit]
 Description=Docker Application Container Engine
@@ -82,9 +119,9 @@ EOF
 
   # configuration for dockerd
   mkdir -p /etc/docker
-  echo "[INFO] generate docker config file"
+  logger debug "generate docker config: /etc/docker/daemon.json"
   if [[ "$REGISTRY_MIRROR" == CN ]];then
-    echo "[INFO] prepare register mirror for $REGISTRY_MIRROR"
+    logger debug "prepare register mirror for $REGISTRY_MIRROR"
     cat > /etc/docker/daemon.json << EOF
 {
   "registry-mirrors": [
@@ -102,7 +139,7 @@ EOF
 }
 EOF
   else
-    echo "[INFO] standard config without registry mirrors"
+    logger debug "standard config without registry mirrors"
     cat > /etc/docker/daemon.json << EOF
 {
   "max-concurrent-downloads": 10,
@@ -118,87 +155,88 @@ EOF
   fi
 
   if [[ -e /etc/centos-release || -e /etc/redhat-release ]]; then
-    echo "[INFO] turn off selinux in CentOS/Redhat"
+    logger debug "turn off selinux in CentOS/Redhat"
     getenforce|grep Disabled || setenforce 0
     sed -i 's/^SELINUX=.*$/SELINUX=disabled/g' /etc/selinux/config
   fi
 
-  echo "[INFO] enable and start docker"
+  logger debug "enable and start docker"
   systemctl enable docker
   systemctl daemon-reload && systemctl restart docker && sleep 4
 }
 
 function get_kubeasz() {
   # check if kubeasz already existed
-  [[ -d "/etc/ansible/roles/kube-node" ]] && { echo "[WARN] kubeasz already existed"; return 0; }
+  [[ -d "$BASE/roles/kube-node" ]] && { logger warn "kubeasz already existed"; return 0; }
 
-  echo -e "[INFO] \033[33mdownloading kubeasz\033[0m $KUBEASZ_VER"
-  echo "[INFO] run a temporary container"
-  docker run -d --name temp_easz easzlab/kubeasz:${KUBEASZ_VER} || { echo "[ERROR] download failed."; exit 1; }
+  logger info "downloading kubeasz: $KUBEASZ_VER"
+  logger debug " run a temporary container"
+  docker run -d --name temp_easz easzlab/kubeasz:${KUBEASZ_VER} || { logger error "download failed."; exit 1; }
 
-  [[ -f "/etc/ansible/down/docker-${DOCKER_VER}.tgz" ]] && /bin/mv -f "/etc/ansible/down/docker-${DOCKER_VER}.tgz" /tmp
-  [[ -d "/etc/ansible/bin" ]] && /bin/mv -f /etc/ansible/bin /tmp
+  [[ -f "$BASE/down/docker-${DOCKER_VER}.tgz" ]] && /bin/mv -f "$BASE/down/docker-${DOCKER_VER}.tgz" /tmp
+  [[ -d "$BASE/bin" ]] && /bin/mv -f $BASE/bin /tmp
 
-  rm -rf /etc/ansible && \
-  echo "[INFO] cp kubeasz code from the temporary container" && \
-  docker cp temp_easz:/etc/ansible /etc/ansible && \
-  echo "[INFO] stop&remove temporary container" && \
+  rm -rf $BASE && \
+  logger debug "cp kubeasz code from the temporary container" && \
+  docker cp temp_easz:$BASE $BASE && \
+  logger debug "stop&remove temporary container" && \
   docker rm -f temp_easz
 
- [[ -f "/tmp/docker-${DOCKER_VER}.tgz" ]] && /bin/mv -f "/tmp/docker-${DOCKER_VER}.tgz" /etc/ansible/down
- [[ -d "/tmp/bin" ]] && /bin/mv -f /tmp/bin/* /etc/ansible/bin
- return 0
+  mkdir -p $BASE/bin
+  [[ -f "/tmp/docker-${DOCKER_VER}.tgz" ]] && /bin/mv -f "/tmp/docker-${DOCKER_VER}.tgz" $BASE/down
+  [[ -d "/tmp/bin" ]] && /bin/mv -f /tmp/bin/* $BASE/bin
+  return 0
 }
 
 function get_k8s_bin() {
-  [[ -f "/etc/ansible/bin/kubelet" ]] && { echo "[WARN] kubernetes binaries existed"; return 0; }
+  [[ -f "$BASE/bin/kubelet" ]] && { logger warn "kubernetes binaries existed"; return 0; }
   
-  echo -e "[INFO] \033[33mdownloading kubernetes\033[0m $K8S_BIN_VER binaries"
+  logger info "downloading kubernetes: $K8S_BIN_VER binaries"
   docker pull easzlab/kubeasz-k8s-bin:${K8S_BIN_VER} && \
-  echo "[INFO] run a temporary container" && \
+  logger debug "run a temporary container" && \
   docker run -d --name temp_k8s_bin easzlab/kubeasz-k8s-bin:${K8S_BIN_VER} && \
-  echo "[INFO] cp k8s binaries" && \
-  docker cp temp_k8s_bin:/k8s /etc/ansible/k8s_bin_tmp && \
-  /bin/mv -f /etc/ansible/k8s_bin_tmp/* /etc/ansible/bin && \
-  echo "[INFO] stop&remove temporary container" && \
+  logger debug "cp k8s binaries" && \
+  docker cp temp_k8s_bin:/k8s $BASE/k8s_bin_tmp && \
+  /bin/mv -f $BASE/k8s_bin_tmp/* $BASE/bin && \
+  logger debug "stop&remove temporary container" && \
   docker rm -f temp_k8s_bin && \
-  rm -rf /etc/ansible/k8s_bin_tmp
+  rm -rf $BASE/k8s_bin_tmp
 }
 
 function get_ext_bin() {
-  [[ -f "/etc/ansible/bin/etcdctl" ]] && { echo "[WARN] extral binaries existed"; return 0; }
+  [[ -f "$BASE/bin/etcdctl" ]] && { logger warn "extral binaries existed"; return 0; }
 
-  echo -e "[INFO] \033[33mdownloading extral binaries\033[0m kubeasz-ext-bin:$EXT_BIN_VER"
+  logger info "downloading extral binaries kubeasz-ext-bin:$EXT_BIN_VER"
   docker pull easzlab/kubeasz-ext-bin:${EXT_BIN_VER} && \
-  echo "[INFO] run a temporary container" && \
+  logger debug "run a temporary container" && \
   docker run -d --name temp_ext_bin easzlab/kubeasz-ext-bin:${EXT_BIN_VER} && \
-  echo "[INFO] cp extral binaries" && \
-  docker cp temp_ext_bin:/extra /etc/ansible/extra_bin_tmp && \
-  /bin/mv -f /etc/ansible/extra_bin_tmp/* /etc/ansible/bin && \
-  echo "[INFO] stop&remove temporary container" && \
+  logger debug "cp extral binaries" && \
+  docker cp temp_ext_bin:/extra $BASE/extra_bin_tmp && \
+  /bin/mv -f $BASE/extra_bin_tmp/* $BASE/bin && \
+  logger debug "stop&remove temporary container" && \
   docker rm -f temp_ext_bin && \
-  rm -rf /etc/ansible/extra_bin_tmp
+  rm -rf $BASE/extra_bin_tmp
 }
 
 function get_sys_pkg() {
-  [[ -f "/etc/ansible/down/packages/chrony_xenial.tar.gz" ]] && { echo "[WARN] system packages existed"; return 0; }
+  [[ -f "$BASE/down/packages/chrony_xenial.tar.gz" ]] && { logger warn "system packages existed"; return 0; }
 
-  echo -e "[INFO] \033[33mdownloading system packages\033[0m kubeasz-sys-pkg:$SYS_PKG_VER"
+  logger info "downloading system packages kubeasz-sys-pkg:$SYS_PKG_VER"
   docker pull easzlab/kubeasz-sys-pkg:${SYS_PKG_VER} && \
-  echo "[INFO] run a temporary container" && \
+  logger debug "run a temporary container" && \
   docker run -d --name temp_sys_pkg easzlab/kubeasz-sys-pkg:${SYS_PKG_VER} && \
-  echo "[INFO] cp system packages" && \
-  docker cp temp_sys_pkg:/packages /etc/ansible/down && \
-  echo "[INFO] stop&remove temporary container" && \
+  logger debug "cp system packages" && \
+  docker cp temp_sys_pkg:/packages $BASE/down && \
+  logger debug "stop&remove temporary container" && \
   docker rm -f temp_sys_pkg
 }
 
 function get_offline_image() {
 
-  imageDir=/etc/ansible/down
-  [[ -d "$imageDir" ]] || { echo "[ERROR] $imageDir not existed!"; exit 1; }
+  imageDir=$BASE/down
+  [[ -d "$imageDir" ]] || { logger error "$imageDir not existed!"; exit 1; }
   
-  echo -e "[INFO] \033[33mdownloading offline images\033[0m"
+  logger info "downloading offline images"
 
   if [[ ! -f "$imageDir/calico_$calicoVer.tar" ]];then
     docker pull "calico/cni:${calicoVer}" && \
@@ -239,6 +277,7 @@ function get_offline_image() {
 }
 
 function download_all() {
+  mkdir -p /opt/kube/bin "$BASE/down" "$BASE/bin"
   download_docker && \
   install_docker && \
   get_kubeasz && \
@@ -248,16 +287,17 @@ function download_all() {
 }
 
 function start_kubeasz_docker() {
-  [[ -d "/etc/ansible/roles/kube-node" ]] || { echo "[ERROR] not initialized. try 'easzup -D' first."; exit 1; }
+  [[ -d "$BASE/roles/kube-node" ]] || { logger error "not initialized. try 'ezdown -D' first."; exit 1; }
 
+  logger info "try to run kubeasz in a container"
   # get host's IP
   host_if=$(ip route|grep default|cut -d' ' -f5)
   host_ip=$(ip a|grep "$host_if$"|awk '{print $2}'|cut -d'/' -f1)
-  echo "[INFO] get host IP: $host_ip"
+  logger debug "get host IP: $host_ip"
 
   # allow ssh login using key locally
   if [[ ! -e /root/.ssh/id_rsa ]]; then
-    echo "[INFO] generate ssh key pair"
+    logger debug "generate ssh key pair"
     ssh-keygen -t rsa -b 2048 -N '' -f /root/.ssh/id_rsa > /dev/null
     cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
     ssh-keyscan -t ecdsa -H "$host_ip" >> /root/.ssh/known_hosts
@@ -265,20 +305,19 @@ function start_kubeasz_docker() {
 
   # create a link '/usr/bin/python' in Ubuntu1604
   if [[ ! -e /usr/bin/python && -e /etc/debian_version ]]; then
-    echo "[INFO] create a soft link '/usr/bin/python'"
+    logger debug "create a soft link '/usr/bin/python'"
     ln -s /usr/bin/python3 /usr/bin/python
   fi
 
   # 
-  docker load -i /etc/ansible/down/kubeasz_${KUBEASZ_VER}.tar
+  docker load -i $BASE/down/kubeasz_${KUBEASZ_VER}.tar
 
   # run kubeasz docker container
-  echo "[INFO] run kubeasz in a container"
   docker run --detach \
       --name kubeasz \
       --restart always \
       --env HOST_IP="$host_ip" \
-      --volume /etc/ansible:/etc/ansible \
+      --volume $BASE:$BASE \
       --volume /root/.kube:/root/.kube \
       --volume /root/.ssh/id_rsa:/root/.ssh/id_rsa:ro \
       --volume /root/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro \
@@ -287,35 +326,19 @@ function start_kubeasz_docker() {
 }
 
 function clean_container() {
- echo "[INFO] clean all running containers"
+ logger info "clean all running containers"
  docker ps -a|awk 'NR>1{print $1}'|xargs docker rm -f 
 } 
 
-function usage() {
-  cat <<EOF
-Usage: easzup [options] [args]
-  option: -{DdekSz}
-    -C         stop&clean all local containers
-    -D         download all into /etc/ansible
-    -P         download system packages for offline installing
-    -S         start kubeasz in a container
-    -d <ver>   set docker-ce version, default "$DOCKER_VER"
-    -e <ver>   set kubeasz-ext-bin version, default "$EXT_BIN_VER"
-    -k <ver>   set kubeasz-k8s-bin version, default "$K8S_BIN_VER"
-    -m <str>   set docker registry mirrors, default "CN"(used in Mainland,China)
-    -p <ver>   set kubeasz-sys-pkg version, default "$SYS_PKG_VER"
-    -z <ver>   set kubeasz version, default "$KUBEASZ_VER"
-  
-see more at https://github.com/kubeasz/dockerfiles
-EOF
-} 
 
 ### Main Lines ##################################################
 function main() {
+  BASE="/etc/kubeasz"
+
   # check if use bash shell
-  readlink /proc/$$/exe|grep -q "dash" && { echo "[ERROR] you should use bash shell, not sh"; exit 1; }
+  readlink /proc/$$/exe|grep -q "dash" && { logger error "you should use bash shell, not sh"; exit 1; }
   # check if use with root
-  [[ "$EUID" -ne 0 ]] && { echo "[ERROR] you should run this script as root"; exit 1; }
+  [[ "$EUID" -ne 0 ]] && { logger error "you should run this script as root"; exit 1; }
   
   [[ "$#" -eq 0 ]] && { usage >&2; exit 1; }
   
@@ -360,12 +383,12 @@ function main() {
       esac
   done
   
-  [[ "$ACTION" == "" ]] && { echo "[ERROR] illegal option"; usage; exit 1; }
+  [[ "$ACTION" == "" ]] && { logger error "illegal option"; usage; exit 1; }
   
   # excute cmd "$ACTION" 
-  echo -e "[INFO] \033[33mAction begin\033[0m : $ACTION"
-  ${ACTION} || { echo -e "[ERROR] \033[31mAction failed\033[0m : $ACTION"; return 1; }
-  echo -e "[INFO] \033[32mAction successed\033[0m : $ACTION"
+  logger info "Action begin: $ACTION"
+  ${ACTION} || { logger error "Action failed: $ACTION"; return 1; }
+  logger info "Action successed: $ACTION"
 }
 
 main "$@"
