fix: 移除 wget 的 user-agent 参数以修复清华源 403 问题
移除 wget 命令中的 `--user-agent="Mozilla"` 参数

diff --git a/ezdown b/ezdown
--- a/ezdown
+++ b/ezdown
@@ -170,7 +170,7 @@ function download_docker() {
   else
     logger info "downloading docker binaries, arch:$ARCH, version:$DOCKER_VER"
     if [[ -e /usr/bin/wget ]];then
-      wget -c --user-agent="Mozilla" --no-check-certificate "$DOCKER_URL" || { logger error "downloading docker failed"; exit 1; }
+      wget -c --no-check-certificate "$DOCKER_URL" || { logger error "downloading docker failed"; exit 1; }
     else
       curl -k -C- -O --retry 3 "$DOCKER_URL" || { logger error "downloading docker failed"; exit 1; }
     fi
