fix:nf_conntrack模块安装判断等

diff --git a/ezdown b/ezdown
--- a/ezdown
+++ b/ezdown
@@ -86,10 +86,10 @@ function download_docker() {
     logger warn "docker binaries already existed"
   else
     logger info "downloading docker binaries, version $DOCKER_VER"
-    if [[ -e /usr/bin/curl ]];then
-      curl -C- -O --retry 3 "$DOCKER_URL" || { logger error "downloading docker failed"; exit 1; }
+    if [[ -e /usr/bin/wget ]];then
+      wget -c --no-check-certificate "$DOCKER_URL" || { logger error "downloading docker failed"; exit 1; }
     else
-      wget -c "$DOCKER_URL" || { logger error "downloading docker failed"; exit 1; }
+      curl -k -C- -O --retry 3 "$DOCKER_URL" || { logger error "downloading docker failed"; exit 1; }
     fi
     /bin/mv -f "./docker-$DOCKER_VER.tgz" "$BASE/down"
   fi
@@ -345,7 +345,7 @@ function start_kubeasz_docker() {
   fi
 
   # create a link '/usr/bin/python' in Ubuntu1604
-  if [[ ! -e /usr/bin/python && -e /etc/debian_version ]]; then
+  if [[ ! -e /usr/bin/python && -e /usr/bin/python3 ]]; then
     logger debug "create a soft link '/usr/bin/python'"
     ln -s /usr/bin/python3 /usr/bin/python
   fi
