加速docker pull下载速度

diff --git a/tools/easzup b/tools/easzup
--- a/tools/easzup
+++ b/tools/easzup
@@ -123,7 +123,7 @@ function get_kubeasz() {
 
   echo -e "[INFO] \033[33mdownloading kubeasz\033[0m $KUBEASZ_VER"
   echo "[INFO] run a temporary container"
-  docker run -d --name temp_easz easzlab/kubeasz:${KUBEASZ_VER} || { echo "[ERROR] download failed."; exit 1; }
+  docker run -d --name temp_easz dockerhub.azk8s.cn/easzlab/kubeasz:${KUBEASZ_VER} || { echo "[ERROR] download failed."; exit 1; }
 
   [[ -f "/etc/ansible/down/docker-${DOCKER_VER}.tgz" ]] && mv "/etc/ansible/down/docker-${DOCKER_VER}.tgz" /tmp
 
@@ -141,9 +141,9 @@ function get_k8s_bin() {
   [[ -f "/etc/ansible/bin/kubelet" ]] && { echo "[WARN] kubernetes binaries existed"; return 0; }
   
   echo -e "[INFO] \033[33mdownloading kubernetes\033[0m $K8S_BIN_VER binaries"
-  docker pull easzlab/kubeasz-k8s-bin:${K8S_BIN_VER} && \
+  docker pull dockerhub.azk8s.cn/easzlab/kubeasz-k8s-bin:${K8S_BIN_VER} && \
   echo "[INFO] run a temporary container" && \
-  docker run -d --name temp_k8s_bin easzlab/kubeasz-k8s-bin:${K8S_BIN_VER} && \
+  docker run -d --name temp_k8s_bin dockerhub.azk8s.cn/easzlab/kubeasz-k8s-bin:${K8S_BIN_VER} && \
   echo "[INFO] cp k8s binaries" && \
   docker cp temp_k8s_bin:/k8s /k8s_bin_tmp && \
   mv /k8s_bin_tmp/* /etc/ansible/bin && \
@@ -156,9 +156,9 @@ function get_ext_bin() {
   [[ -f "/etc/ansible/bin/etcdctl" ]] && { echo "[WARN] extral binaries existed"; return 0; }
 
   echo -e "[INFO] \033[33mdownloading extral binaries\033[0m kubeasz-ext-bin:$EXT_BIN_VER"
-  docker pull easzlab/kubeasz-ext-bin:${EXT_BIN_VER} && \
+  docker pull dockerhub.azk8s.cn/easzlab/kubeasz-ext-bin:${EXT_BIN_VER} && \
   echo "[INFO] run a temporary container" && \
-  docker run -d --name temp_ext_bin easzlab/kubeasz-ext-bin:${EXT_BIN_VER} && \
+  docker run -d --name temp_ext_bin dockerhub.azk8s.cn/easzlab/kubeasz-ext-bin:${EXT_BIN_VER} && \
   echo "[INFO] cp extral binaries" && \
   docker cp temp_ext_bin:/extra /extra_bin_tmp && \
   mv /extra_bin_tmp/* /etc/ansible/bin && \
@@ -171,9 +171,9 @@ function get_sys_pkg() {
   [[ -f "/etc/ansible/down/packages/chrony_xenial.tar.gz" ]] && { echo "[WARN] system packages existed"; return 0; }
 
   echo -e "[INFO] \033[33mdownloading system packages\033[0m kubeasz-sys-pkg:$SYS_PKG_VER"
-  docker pull easzlab/kubeasz-sys-pkg:${SYS_PKG_VER} && \
+  docker pull dockerhub.azk8s.cn/easzlab/kubeasz-sys-pkg:${SYS_PKG_VER} && \
   echo "[INFO] run a temporary container" && \
-  docker run -d --name temp_sys_pkg easzlab/kubeasz-sys-pkg:${SYS_PKG_VER} && \
+  docker run -d --name temp_sys_pkg dockerhub.azk8s.cn/easzlab/kubeasz-sys-pkg:${SYS_PKG_VER} && \
   echo "[INFO] cp system packages" && \
   docker cp temp_sys_pkg:/packages /etc/ansible/down && \
   echo "[INFO] stop&remove temporary container" && \
@@ -197,42 +197,42 @@ function get_offline_image() {
   echo -e "[INFO] \033[33mdownloading offline images\033[0m"
 
   if [[ ! -f "$imageDir/calico_$calicoVer.tar" ]];then
-    docker pull calico/cni:${calicoVer} && \
-    docker pull calico/kube-controllers:${calicoVer} && \
-    docker pull calico/node:${calicoVer} && \
-    docker save -o ${imageDir}/calico_${calicoVer}.tar calico/cni:${calicoVer} calico/kube-controllers:${calicoVer} calico/node:${calicoVer}
+    docker pull dockerhub.azk8s.cn/calico/cni:${calicoVer} && \
+    docker pull dockerhub.azk8s.cn/calico/kube-controllers:${calicoVer} && \
+    docker pull dockerhub.azk8s.cn/calico/node:${calicoVer} && \
+    docker save -o ${imageDir}/calico_${calicoVer}.tar dockerhub.azk8s.cn/calico/cni:${calicoVer} dockerhub.azk8s.cn/calico/kube-controllers:${calicoVer} dockerhub.azk8s.cn/calico/node:${calicoVer}
   fi
   if [[ ! -f "$imageDir/coredns_$corednsVer.tar" ]];then
-    docker pull coredns/coredns:${corednsVer} && \
-    docker save -o ${imageDir}/coredns_${corednsVer}.tar coredns/coredns:${corednsVer}
+    docker pull dockerhub.azk8s.cn/coredns/coredns:${corednsVer} && \
+    docker save -o ${imageDir}/coredns_${corednsVer}.tar dockerhub.azk8s.cn/coredns/coredns:${corednsVer}
   fi
   if [[ ! -f "$imageDir/dashboard_$dashboardVer.tar" ]];then
-    docker pull kubernetesui/dashboard:${dashboardVer} && \
-    docker save -o ${imageDir}/dashboard_${dashboardVer}.tar kubernetesui/dashboard:${dashboardVer}
+    docker pull dockerhub.azk8s.cn/kubernetesui/dashboard:${dashboardVer} && \
+    docker save -o ${imageDir}/dashboard_${dashboardVer}.tar dockerhub.azk8s.cn/kubernetesui/dashboard:${dashboardVer}
   fi
   if [[ ! -f "$imageDir/flannel_$flannelVer.tar" ]];then
-    docker pull easzlab/flannel:${flannelVer} && \
-    docker save -o ${imageDir}/flannel_${flannelVer}.tar easzlab/flannel:${flannelVer}
+    docker pull dockerhub.azk8s.cn/easzlab/flannel:${flannelVer} && \
+    docker save -o ${imageDir}/flannel_${flannelVer}.tar dockerhub.azk8s.cn/easzlab/flannel:${flannelVer}
   fi
   if [[ ! -f "$imageDir/metrics-scraper_$dashboardMetricsScraperVer.tar" ]];then
-    docker pull kubernetesui/metrics-scraper:${dashboardMetricsScraperVer} && \
-    docker save -o ${imageDir}/metrics-scraper_${dashboardMetricsScraperVer}.tar kubernetesui/metrics-scraper:${dashboardMetricsScraperVer}
+    docker pull dockerhub.azk8s.cn/kubernetesui/metrics-scraper:${dashboardMetricsScraperVer} && \
+    docker save -o ${imageDir}/metrics-scraper_${dashboardMetricsScraperVer}.tar dockerhub.azk8s.cn/kubernetesui/metrics-scraper:${dashboardMetricsScraperVer}
   fi
   if [[ ! -f "$imageDir/metrics-server_$metricsVer.tar" ]];then
-    docker pull mirrorgooglecontainers/metrics-server-amd64:${metricsVer} && \
-    docker save -o ${imageDir}/metrics-server_${metricsVer}.tar mirrorgooglecontainers/metrics-server-amd64:${metricsVer}
+    docker pull dockerhub.azk8s.cn/mirrorgooglecontainers/metrics-server-amd64:${metricsVer} && \
+    docker save -o ${imageDir}/metrics-server_${metricsVer}.tar dockerhub.azk8s.cn/mirrorgooglecontainers/metrics-server-amd64:${metricsVer}
   fi
   if [[ ! -f "$imageDir/pause_$pauseVer.tar" ]];then
-    docker pull mirrorgooglecontainers/pause-amd64:${pauseVer} && \
-    docker save -o ${imageDir}/pause_${pauseVer}.tar mirrorgooglecontainers/pause-amd64:${pauseVer}
+    docker pull dockerhub.azk8s.cn/mirrorgooglecontainers/pause-amd64:${pauseVer} && \
+    docker save -o ${imageDir}/pause_${pauseVer}.tar dockerhub.azk8s.cn/mirrorgooglecontainers/pause-amd64:${pauseVer}
   fi
   if [[ ! -f "$imageDir/traefik_$traefikVer.tar" ]];then
-    docker pull traefik:${traefikVer} && \
-    docker save -o ${imageDir}/traefik_${traefikVer}.tar traefik:${traefikVer}
+    docker pull dockerhub.azk8s.cn/traefik:${traefikVer} && \
+    docker save -o ${imageDir}/traefik_${traefikVer}.tar dockerhub.azk8s.cn/traefik:${traefikVer}
   fi
   if [[ ! -f "$imageDir/kubeasz_$KUBEASZ_VER.tar" ]];then
-    docker pull easzlab/kubeasz:${KUBEASZ_VER} && \
-    docker save -o ${imageDir}/kubeasz_${KUBEASZ_VER}.tar easzlab/kubeasz:${KUBEASZ_VER}
+    docker pull dockerhub.azk8s.cn/easzlab/kubeasz:${KUBEASZ_VER} && \
+    docker save -o ${imageDir}/kubeasz_${KUBEASZ_VER}.tar dockerhub.azk8s.cn/easzlab/kubeasz:${KUBEASZ_VER}
   fi
 }
 
@@ -281,7 +281,7 @@ function start_kubeasz_docker() {
       --volume /root/.ssh/id_rsa:/root/.ssh/id_rsa:ro \
       --volume /root/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro \
       --volume /root/.ssh/known_hosts:/root/.ssh/known_hosts:ro \
-      easzlab/kubeasz:${KUBEASZ_VER} sleep 36000
+      dockerhub.azk8s.cn/easzlab/kubeasz:${KUBEASZ_VER} sleep 36000
 }
 
 function clean_container() {
